apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    user: admin
    secureJsonData:
      token: admin-token
    jsonData:
      version: Flux
      organization: ecommerce-org
      defaultBucket: events
      tlsSkipVerify: true
    isDefault: true
    editable: true

  - name: MySQL
    type: mysql
    url: mysql-db:3306
    database: ecommerce
    user: user
    secureJsonData:
      password: password
    jsonData:
      maxOpenConns: 100
      maxIdleConns: 100
      maxConnLifetime: 14400
    editable: true